name: Run unit tests ğŸ§ª
on: [push]
permissions:
  contents: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install dependencies ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - run: npm ci

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests ğŸ§ª
        run: npm run test:unit

  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run mutation tests ğŸ§ª
        run: npm run test:mutation

  deploy-test-report:
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - mutation-test
    steps:
      - name: Deploy test report ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: test-report
